version: '3.4'

services:
  a11ytable:
    image: mockserver
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:3000
